/* Atelier Obsidian: a reusable, product-first data layer that separates object facts, imagery, material reasoning, and request language from presentation components. */
export type ProductGalleryFrame = { id: string; label: string; caption: string; image: string; fallback?: string; alt: string; position?: string };
export type ProductVariant = { id: string; label: string; image: string; alt: string; availabilityNote: string };
export type PresentationFrame = Pick<ProductGalleryFrame, "label" | "caption" | "image">;
export type ProductSpecGroup = { label: string; items: { label: string; value: string }[] };
export type ProductFeature = { label: string; title: string; emphasis: string; body: string; image: string; alt: string };
export type Availability = { label: string; action: string; note: string; longNote: string };
export type ProductDetail = { gallery: ProductGalleryFrame[]; specifications: ProductSpecGroup[]; technicalIntro: string; movement: ProductFeature; material: ProductFeature; craft: { title: string; body: string; image: string; alt: string }[]; availability: Availability };
export type Watch = { slug: string; reference: string; name: string; family: string; short: string; description: string; image: string; year: string; price: string; case: string; dial: string; strap: string; movement: string; reserve: string; water: string; frequency: string; dimensions: string; materials: readonly string[]; note: string; designPhilosophy: string; materialRationale: string; context: string; variants: readonly ProductVariant[]; presentation?: PresentationFrame[]; detail: ProductDetail };

const assets = {
  meridian: "/manus-storage/samay-meridian-product_5610b9bd.jpg", serein: "/manus-storage/samay-serein-product_147168aa.jpg", vesper: "/manus-storage/samay-vesper-product_0b2003dc.jpg",
  dial: "/manus-storage/samay-macro-dial_8993792c.jpg", case: "/manus-storage/samay-case-profile_d72bd80f.jpg", crown: "/manus-storage/samay-crown-detail_6c531800.jpg", movement: "/manus-storage/samay-movement-study_129e7db4.jpg", tools: "/manus-storage/samay-atelier-tools_ad9fdca5.jpg",
  meridianBack: "/manus-storage/samay-movement-study_129e7db4.jpg", meridianCrown: "/manus-storage/samay-case-profile_d72bd80f.jpg", meridianDial: "/manus-storage/samay-macro-dial_8993792c.jpg", sereinBracelet: "/manus-storage/samay-serein-product_147168aa.jpg", vesperBack: "/manus-storage/samay-movement-study_129e7db4.jpg",
};

const availability = (label: string, note: string): Availability => ({ label, action: label === "Private viewing" ? "Request a private viewing" : "Request availability", note, longNote: "This reference is presented for private examination. Share a preferred city or time of week and the house will prepare the appropriate next conversation." });
const commonSpec = (watch: Pick<Watch, "case" | "dial" | "strap" | "movement" | "reserve" | "water" | "frequency" | "materials">, jewels: string, crystal: string) => [
  { label: "Case", items: [{ label: "Dimensions", value: watch.case }, { label: "Material", value: watch.materials[0] }, { label: "Crystal", value: crystal }, { label: "Water resistance", value: watch.water }] },
  { label: "Movement", items: [{ label: "Calibre", value: watch.movement }, { label: "Frequency", value: watch.frequency }, { label: "Power reserve", value: watch.reserve }, { label: "Jewels", value: jewels }] },
  { label: "Dial", items: [{ label: "Construction", value: watch.dial }, { label: "Indices", value: "Applied, hand-finished" }, { label: "Hands", value: "Faceted, polished" }] },
  { label: "Strap", items: [{ label: "Material", value: watch.strap }, { label: "Attachment", value: "Quick-release spring bars" }, { label: "Clasp", value: "Signed pin buckle" }] },
] as ProductSpecGroup[];

const meridianBase = { slug: "meridian", reference: "NO. 01 / SM-039", name: "Meridian", family: "Dress", short: "A study in proportion.", description: "Meridian reduces the dress watch to its essential gestures: a warm ivory dial, a drawn case profile, and the quiet tension of a small seconds hand.", image: assets.meridian, year: "2026", price: "By private request", case: "39 mm / 9.2 mm", dial: "Warm ivory, sector construction", strap: "Dark calfskin / pin buckle", movement: "SM-101 hand-wound calibre", reserve: "60 hours", water: "5 bar", frequency: "21,600 vph", dimensions: "39 × 46.2 × 9.2 mm", materials: ["Brushed 316L steel", "Sapphire crystal", "Hand-finished calfskin"], note: "The case is drawn from a single continuous profile. Its polished bevel catches light only when the wrist turns.", designPhilosophy: "Meridian is the house's first exercise in reduction: an everyday mechanical watch with the confidence to leave the dial quiet.", materialRationale: "Brushed steel holds the body of the light; the polished bevel is reserved for movement. Calfskin softens the object without making it casual.", context: "For late trains, long tables, and the unremarked hours between them." } as const;
const sereinBase = { slug: "serein", reference: "NO. 02 / SM-040", name: "Serein", family: "Everyday", short: "Legibility, held in balance.", description: "Serein is the most direct expression of the house: an exacting slate dial, articulated steel, and a case that wears with unforced ease.", image: assets.serein, year: "2026", price: "By private request", case: "40 mm / 10.1 mm", dial: "Slate grey, applied batons", strap: "Articulated steel bracelet", movement: "SM-201 automatic calibre", reserve: "55 hours", water: "10 bar", frequency: "28,800 vph", dimensions: "40 × 47.5 × 10.1 mm", materials: ["Brushed and polished 316L steel", "Domed sapphire crystal", "Solid steel bracelet"], note: "The bracelet tapers by hand, link by link, until the case appears to settle naturally against the wrist.", designPhilosophy: "Serein is the direct piece: generous enough to read at a glance, measured enough to disappear beneath a cuff.", materialRationale: "A satin body gives the bracelet its calm; small polished links return just enough light to keep the wrist moving.", context: "For the workday that becomes dinner, and the city that does not require a change of watch." } as const;
const vesperBase = { slug: "vesper", reference: "NO. 03 / SM-041", name: "Vesper", family: "Complication", short: "Depth, measured in shadow.", description: "Vesper uses darkness as a material. A smoked steel case, a discreet power reserve, and one oxblood seconds hand set the rhythm without raising its voice.", image: assets.vesper, year: "2026", price: "By private request", case: "41 mm / 10.8 mm", dial: "Charcoal, power reserve aperture", strap: "Espresso calfskin / pin buckle", movement: "SM-301 manual calibre", reserve: "72 hours", water: "5 bar", frequency: "21,600 vph", dimensions: "41 × 48.1 × 10.8 mm", materials: ["Smoked steel", "Sapphire crystal", "Espresso calfskin"], note: "The red hand is the only interruption. It gives the eye a point of return, then disappears into the dial again.", designPhilosophy: "Vesper is the technical reference expressed through restraint: a complication that keeps its voice low.", materialRationale: "Smoked steel absorbs the room; the oxblood hand is a functional accent, not decoration. Espresso leather keeps the palette grounded.", context: "For departures after dark, when a small indication is more useful than a larger statement." } as const;

export const watches: Watch[] = [
  { ...meridianBase, variants: [{ id: "steel-ivory-calfskin", label: "Steel / ivory / calfskin", image: assets.meridian, alt: "SAMAY Meridian in brushed steel with an ivory sector dial and dark calfskin strap", availabilityNote: "The photographed steel, ivory, and calfskin configuration is prepared individually for examination and discussion." }], presentation: [{ label: "Exterior", caption: "The complete object, held in a single line.", image: assets.meridian }], detail: { gallery: [
    { id: "exterior", label: "Exterior", caption: "The complete object, held in a single line.", image: assets.meridian, alt: "SAMAY Meridian warm ivory dial dress watch on a dark stone plinth" },
    { id: "dial", label: "Dial", caption: "Warm ivory, with room for the eye to settle.", image: assets.meridianDial, fallback: assets.dial, alt: "Macro study of the SAMAY Meridian warm ivory sector dial" },
    { id: "crown", label: "Crown", caption: "The smallest point of contact, considered as carefully as the dial.", image: assets.meridianCrown, fallback: assets.crown, alt: "SAMAY Meridian brushed steel case and crown in side profile" },
    { id: "rear", label: "Caseback", caption: "The hand-wound calibre, viewed through sapphire.", image: assets.meridianBack, fallback: assets.meridian, alt: "SAMAY Meridian exhibition caseback with a hand-wound calibre" },
  ], specifications: commonSpec(meridianBase, "24", "Box sapphire, anti-reflective"), technicalIntro: "The figures are the operating conditions of the object: the dimensions that place it on the wrist, and the measured rhythm under its dial.", movement: { label: "SM-101 / Hand-wound", title: "A movement", emphasis: "kept close.", body: "SM-101 is hand-wound to keep the Meridian case thin and the daily interaction direct. Its two-thirds plate holds the train in one calm field; regulation is kept to five positions before casing.", image: assets.meridianBack, alt: "SAMAY Meridian caseback revealing the hand-wound SM-101 calibre" }, material: { label: "Brushed steel", title: "The case", emphasis: "holds the light.", body: "The steel is brushed across its broad planes, then interrupted by a narrow polished bevel. That small shift in finish makes the profile visible only when the wrist moves.", image: assets.meridianCrown, alt: "SAMAY Meridian brushed steel case and crown detail" }, craft: [{ title: "Sector dial", body: "The sector construction opens the ivory surface without breaking its quiet. The small seconds register is kept low enough to feel discovered, not announced.", image: assets.meridianDial, alt: "Macro study of the Meridian sector dial" }, { title: "Case edge", body: "A continuous brushed plane gives way to one polished edge. The transition is restrained so the case stays drawn rather than jeweled.", image: assets.meridianCrown, alt: "Meridian case edge and crown detail" }, { title: "Hand-wound", body: "Winding is not treated as theatre. It is the short, physical reminder that the mechanism is close at hand.", image: assets.meridianBack, alt: "Meridian exhibition caseback mechanical study" }], availability: availability("Available for private request", "Prepared individually for examination and discussion.") } },
  { ...sereinBase, variants: [{ id: "steel-slate-bracelet", label: "Steel / slate / bracelet", image: assets.serein, alt: "SAMAY Serein in steel with a slate dial and articulated steel bracelet", availabilityNote: "The photographed steel-bracelet configuration is prepared with a bracelet-fitting conversation, by appointment." }], detail: { gallery: [
    { id: "exterior", label: "Exterior", caption: "The full reference, resolved in steel and slate.", image: assets.serein, alt: "SAMAY Serein slate dial steel bracelet watch on a stone plinth" },
    { id: "bracelet", label: "Bracelet", caption: "Articulated links taper until the case settles against the wrist.", image: assets.sereinBracelet, fallback: assets.serein, position: "88% 50%", alt: "SAMAY Serein bracelet and steel case detail" },
  ], specifications: commonSpec(sereinBase, "26", "Domed sapphire, anti-reflective"), technicalIntro: "Serein is regulated for a longer working day: automatic winding, a balanced steel bracelet, and a water resistance that keeps the object useful without changing its tone.", movement: { label: "SM-201 / Automatic", title: "A rhythm", emphasis: "that follows.", body: "The automatic calibre follows the movement of the wrist rather than asking for attention. Its architecture is specified for steadiness, readability, and a case that remains compact under a cuff.", image: assets.sereinBracelet, alt: "SAMAY Serein steel bracelet and case study" }, material: { label: "Articulated steel", title: "A bracelet", emphasis: "that settles.", body: "Satin-finished links create a continuous field from case to clasp. Small polished interruptions return just enough light to make the bracelet legible in motion.", image: assets.sereinBracelet, alt: "SAMAY Serein articulated steel bracelet detail" }, craft: [{ title: "Slate dial", body: "The dial is deliberately low contrast. Applied batons catch daylight at their edge, leaving the surface calm from a distance.", image: assets.serein, alt: "SAMAY Serein slate dial exterior view" }, { title: "Link taper", body: "The bracelet narrows in small steps rather than one gesture. It changes the weight of the object before it changes the look.", image: assets.sereinBracelet, alt: "SAMAY Serein steel bracelet macro view" }, { title: "Domed crystal", body: "The crystal gives the dial room to breathe, then disappears as the watch settles into the wrist's line of sight.", image: assets.serein, alt: "SAMAY Serein domed crystal and slate dial view" }], availability: availability("Available for private request", "Prepared with a bracelet fitting conversation, by appointment.") } },
  { ...vesperBase, variants: [{ id: "smoked-steel-charcoal-calfskin", label: "Smoked steel / charcoal / calfskin", image: assets.vesper, alt: "SAMAY Vesper in smoked steel with a charcoal dial and espresso calfskin strap", availabilityNote: "The photographed smoked-steel and calfskin configuration is a technical reference prepared for a slower, private examination." }], detail: { gallery: [
    { id: "exterior", label: "Exterior", caption: "A technical reference, resolved in smoke and shadow.", image: assets.vesper, alt: "SAMAY Vesper charcoal dial watch on a dark stone plinth" },
    { id: "rear", label: "Caseback", caption: "The hand-wound movement, held behind a smoked steel case.", image: assets.vesperBack, fallback: assets.vesper, alt: "SAMAY Vesper exhibition caseback with a hand-wound mechanical movement" },
  ], specifications: commonSpec(vesperBase, "27", "Box sapphire, anti-reflective"), technicalIntro: "Vesper carries its complication in a measured register. The proportions remain composed while the power reserve indication makes the mechanism useful across longer, darker hours.", movement: { label: "SM-301 / Manual", title: "A reserve", emphasis: "kept in view.", body: "The manual SM-301 places its power reserve indication in the dial's shadow rather than at its center. The complication is a practical measure: enough information, given at the appropriate volume.", image: assets.vesperBack, alt: "SAMAY Vesper exhibition caseback and manual mechanical movement" }, material: { label: "Smoked steel", title: "Steel,", emphasis: "turned inward.", body: "The smoked finish absorbs the room before returning a small line at the case edge. It keeps the power reserve and oxblood seconds hand as the only purposeful interruptions.", image: assets.vesper, alt: "SAMAY Vesper smoked steel case and charcoal dial study" }, craft: [{ title: "Power reserve", body: "The indication is recessed into the dial's field so its function becomes part of the composition, not a separate event.", image: assets.vesper, alt: "SAMAY Vesper charcoal dial with power reserve indication" }, { title: "Smoked case", body: "The case is finished to absorb broad light. Its edges are left clear enough to keep the proportions readable in shadow.", image: assets.vesper, alt: "SAMAY Vesper smoked steel case view" }, { title: "Manual reserve", body: "A longer reserve gives the complication a practical rhythm. Wind the watch when the hand asks, not because the interface insists.", image: assets.vesperBack, alt: "SAMAY Vesper caseback mechanical study" }], availability: availability("Private viewing", "A technical reference prepared for a slower, private examination.") } },
];

export type MaterialEntry = { name: string; descriptor: string; body: string; finish: string; uses: string; tone: string };
export const materials: MaterialEntry[] = [
  { name: "Steel", descriptor: "The body of the light.", body: "316L steel is brushed until it holds a soft, even plane, then polished only at the edges where the wrist turns.", finish: "Brushed plane / polished bevel", uses: "Cases, crowns, bracelets", tone: "Cool, exact, familiar" }, { name: "Titanium", descriptor: "Weight, removed.", body: "A lighter metal with a quieter surface. Its grain changes the way a case sits against the wrist and the room.", finish: "Bead-blasted / satin", uses: "Lightweight case studies", tone: "Dry, quiet, architectural" }, { name: "Ceramic", descriptor: "A surface without noise.", body: "Dense and resistant, ceramic gives the darkest references their calm. It asks the light to arrive deliberately.", finish: "Matte / micro-bevel", uses: "Dark case experiments", tone: "Absorptive, precise, still" }, { name: "Sapphire", descriptor: "The invisible wall.", body: "Crystal is treated as architecture: a transparent plane that protects the dial without interrupting its proportions.", finish: "Domed / anti-reflective", uses: "Crystal, exhibition casebacks", tone: "Clear, deep, protective" }, { name: "Leather", descriptor: "The part that learns.", body: "Calfskin is cut, edged, and left to change. A strap should gather a little history without asking for attention.", finish: "Hand-edged / natural grain", uses: "Straps, travel cases", tone: "Warm, tactile, personal" }, { name: "Gold", descriptor: "A measured accent.", body: "Champagne gold is used sparingly at SAMAY: an index, a pin, a line of light rather than a declaration of value.", finish: "Brushed / restrained polish", uses: "Hands, pins, small details", tone: "Warm, exact, rare" },
];
export const movementSpecs = [["Calibre", "SM-101 hand-wound"], ["Power reserve", "60 hours"], ["Frequency", "21,600 vph"], ["Jewels", "24"], ["Architecture", "Small seconds / twin barrel"], ["Finishing", "Circular graining / hand-bevelled bridges"]] as const;
export const craftSteps = [["01", "Draw", "Proportion begins on paper: case, lugs, and the distance between the eye and the wrist."], ["02", "Finish", "Brushing and polish are repeated until the surface holds an even, low light."], ["03", "Regulate", "Each movement is adjusted to five positions before it is allowed to leave the bench."], ["04", "Return", "A final quiet examination checks the object as a whole, not only its parts."]] as const;
export const servicePrinciples = [["Care", "A watch should be handled often and stored without ceremony: dry, wound, and away from sudden temperature changes."], ["Maintenance", "We recommend a complete service every five to seven years, with a shorter inspection when the rhythm of the movement changes."], ["Continuity", "Every SAMAY service record travels with the watch. The certificate is a record of care, not a claim of rarity."], ["Straps", "A new strap can change the hours a watch belongs to. Our concierge will recommend leather, length, and finish by conversation."]] as const;
export const boutiques = [{ city: "Geneva", note: "A quiet room near the lake, open by appointment Tuesday to Saturday.", hours: "10:00 — 18:00", detail: "Private viewing / movement examination" }, { city: "Paris", note: "A reading-room atmosphere for the collection and the material archive.", hours: "11:00 — 19:00", detail: "Collection / bespoke consultation" }, { city: "New York", note: "A small private salon for the object, the loupe, and a longer conversation.", hours: "10:00 — 18:00", detail: "Collection / service conversation" }];
export const journalEntries = [{ slug: "the-anatomy-of-a-watch", index: "01", category: "Object study", title: "The anatomy of a watch", excerpt: "A case is not a container. It is a sequence of decisions about light, pressure, and the wrist.", image: assets.dial, date: "14.08.2026" }, { slug: "inside-the-movement", index: "02", category: "Atelier notes", title: "Inside the movement", excerpt: "The mechanics remain quiet until a loupe brings them close. Then every surface begins to speak.", image: assets.movement, date: "02.07.2026" }, { slug: "precision-and-proportion", index: "03", category: "Design language", title: "Precision and proportion", excerpt: "Why the smallest changes to a lug, a hand, or a bezel alter the character of the entire watch.", image: assets.case, date: "19.05.2026" }];
export const findWatch = (slug?: string) => watches.find((watch) => watch.slug === slug) ?? watches[0];
export const findJournal = (slug?: string) => journalEntries.find((entry) => entry.slug === slug) ?? journalEntries[0];
