// Atelier Obsidian reminder: the house page should feel like a calm visit to a working atelier, with craft explained specifically.

import { ArrowUpRight } from "lucide-react";
import { ArrowLink, SectionLabel } from "@/components/SiteShell";

const atelierImage = "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=2000&q=85";

export default function Atelier() {
  return <div className="atelier-page section-paper"><section className="atelier-hero section-dark"><div className="atelier-hero__image" style={{ backgroundImage: `url(${atelierImage})` }} /><div className="atelier-hero__copy"><span className="eyebrow">SAMAY / The house</span><h1>Quiet work.<br /><em>Exacting hands.</em></h1><p>We are a contemporary watch house built around the belief that restraint is not a style. It is a method.</p><ArrowLink href="/inquiry" dark>Meet the collection</ArrowLink></div></section><section className="atelier-manifesto section-paper"><div className="section-wrap"><SectionLabel index="01">Our point of view</SectionLabel><div className="atelier-manifesto__grid"><h2>The luxury<br /><em>of attention.</em></h2><div><p className="lead-copy">A watch does not need to announce its value. It needs to reward the person who looks twice.</p><p>SAMAY works between the exacting language of Swiss watchmaking and the slower disciplines of architecture, furniture, and print. We care about the edge a surface makes when it meets another surface. We care about the space around a number. We care about what the wrist feels after six hours.</p></div></div></div></section><section className="craft-sequence section-dark"><div className="section-wrap"><SectionLabel index="02" dark>How we work</SectionLabel><div className="craft-sequence__head"><h2>Four gestures.<br /><em>One object.</em></h2><p>Every reference passes through a sequence that is small enough to stay close to the hand.</p></div><div className="craft-steps">{[["01", "Draw", "Proportion begins on paper: case, lug, dial, and the distance the eye needs to rest."], ["02", "Finish", "Brushing and polish are treated as separate languages, not competing effects."], ["03", "Regulate", "Each movement is adjusted in five positions, then left to settle before inspection."], ["04", "Return", "A final quiet examination checks the object as a whole, not only its individual parts."]].map(([number, title, body]) => <div className="craft-step" key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p><ArrowUpRight size={16} strokeWidth={1.1} /></div>)}</div></div></section><section className="atelier-contact section-paper"><div className="atelier-contact__inner"><div><span className="eyebrow">The atelier / by appointment</span><h2>Come closer<br /><em>to the work.</em></h2></div><div><p>We keep our doors open to conversation: a watch, a loupe, a material sample, and the time to look properly.</p><ArrowLink href="/inquiry">Arrange a private viewing</ArrowLink></div></div></section></div>;
}
