import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Check, RotateCcw, Save } from "lucide-react";
import { Link } from "wouter";
import { ArrowLink, SectionLabel } from "@/components/SiteShell";
import { watches } from "@/lib/samayData";
import { BespokeConfiguration, bespokeStorageKey, configurationId, defaultBespokeConfiguration, restoreBespokeConfiguration } from "@/lib/bespokeConfiguration";
import { trpc } from "@/lib/trpc";
import "@/bespokeExperience.css";

const options = {
  caseMaterial: [["steel", "Brushed steel", "House standard"], ["titanium", "Bead-blasted titanium", "Weight reduced"], ["gold", "Champagne gold", "Measured accent"]],
  dial: [["ivory", "Warm ivory"], ["slate", "Slate grey"], ["charcoal", "Charcoal"]],
  strap: [["leather", "Calfskin"], ["steel", "Articulated steel"], ["rubber", "Textured rubber"]],
  size: [["compact", "Compact", "38 mm study"], ["standard", "Standard", "40 mm study"], ["presence", "Presence", "42 mm study"]],
  movement: [["hand-wound", "Hand-wound", "Direct ritual"], ["automatic", "Automatic", "Daily rhythm"], ["manual-reserve", "Manual reserve", "Longer interval"]],
} as const;
type OptionGroup = keyof typeof options;
const label = (group: OptionGroup, value: string) => options[group].find(item => item[0] === value)?.[1] ?? value;

export default function Bespoke() {
  const [configuration, setConfiguration] = useState<BespokeConfiguration>(() => typeof window === "undefined" ? defaultBespokeConfiguration : restoreBespokeConfiguration(sessionStorage.getItem(bespokeStorageKey)));
  const [saved, setSaved] = useState(false);
  const [requested, setRequested] = useState(false);
  const [error, setError] = useState("");
  const selected = watches.find(item => item.slug === configuration.watch) ?? watches[0];
  const configurationReference = useMemo(() => configurationId(configuration), [configuration]);
  const appointment = trpc.appointment.availability.useQuery().data;
  const requestMutation = trpc.concierge.submit.useMutation({ onSuccess: () => setRequested(true), onError: () => setError("The concierge channel could not prepare this request. Please try again later.") });

  useEffect(() => { sessionStorage.setItem(bespokeStorageKey, JSON.stringify(configuration)); setSaved(false); }, [configuration]);
  const choose = <K extends keyof BespokeConfiguration>(key: K, value: BespokeConfiguration[K]) => setConfiguration(current => ({ ...current, [key]: value }));
  const reset = () => { sessionStorage.removeItem(bespokeStorageKey); setConfiguration(defaultBespokeConfiguration); setSaved(false); };
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name") ?? "").trim(); const email = String(form.get("email") ?? "").trim();
    if (!name || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) { setError("Please include your name and a valid email address."); return; }
    setError(""); requestMutation.mutate({ kind: "bespoke_selection", name, email, reference: `${selected.name} / ${configurationReference}`, message: String(form.get("occasion") ?? "").trim() || undefined, selection: { case: label("caseMaterial", configuration.caseMaterial), dial: label("dial", configuration.dial), strap: label("strap", configuration.strap), occasion: String(form.get("occasion") ?? "").trim() || undefined } });
  };
  const Choice = ({ group, title }: { group: OptionGroup; title: string }) => <fieldset id={group}><legend>{title}</legend><div className={group === "caseMaterial" ? "option-list" : "bespoke-select-grid"}>{options[group].map(([value, name, note]) => <button type="button" key={value} className={configuration[group] === value ? "is-active" : ""} onClick={() => choose(group, value as never)} aria-pressed={configuration[group] === value}><strong>{name}</strong>{note && <small>{note}</small>}</button>)}</div></fieldset>;
  const review: [string, string][] = [["Reference", selected.name], ["Case", label("caseMaterial", configuration.caseMaterial)], ["Dial", label("dial", configuration.dial)], ["Strap / bracelet", label("strap", configuration.strap)], ["Proportion", label("size", configuration.size)], ["Movement preference", label("movement", configuration.movement)]];

  return <div className="flagship-page bespoke-page bespoke-page--complete" data-case={configuration.caseMaterial} data-dial={configuration.dial} data-strap={configuration.strap}>
    <section className="bespoke-hero section-dark"><div className="section-wrap"><SectionLabel index="01" dark>Private selection</SectionLabel><div className="bespoke-hero__grid"><div><h1>Make it<br /><em>your hours.</em></h1><p>A private configuration study, held consistently in the object, review, and consultation notes.</p></div><div className="bespoke-preview bespoke-preview--responsive"><img src={selected.image} alt={`${selected.name} material study: ${label("caseMaterial", configuration.caseMaterial)}, ${label("dial", configuration.dial)}, and ${label("strap", configuration.strap)}`} /><div className="bespoke-preview__state"><span>Visual material study</span><strong>{label("caseMaterial", configuration.caseMaterial)} / {label("dial", configuration.dial)} / {label("strap", configuration.strap)}</strong></div></div></div></div></section>
    <main className="bespoke-flow section-paper"><div className="section-wrap"><nav className="bespoke-flow__rail" aria-label="Bespoke configuration steps"><a href="#caseMaterial">01 Case</a><a href="#dial">02 Dial</a><a href="#strap">03 Strap</a><a href="#movement">04 Movement</a><a href="#review">05 Review</a></nav><section className="bespoke-workbench"><SectionLabel index="02">Frame the object</SectionLabel><div className="bespoke-workbench__grid"><div className="bespoke-controls"><label className="select-label">Reference<select value={configuration.watch} onChange={event => choose("watch", event.target.value)}>{watches.map(item => <option key={item.slug} value={item.slug}>{item.name} / {item.family}</option>)}</select></label><p className="bespoke-controls__notice">The preview is an illustrative material study applied to the photographed reference, not evidence of an available production variant. The house confirms feasibility after review.</p><Choice group="caseMaterial" title="01 — Case" /><Choice group="dial" title="02 — Dial" /><Choice group="strap" title="03 — Strap" /><Choice group="size" title="Proportion preference" /><Choice group="movement" title="04 — Movement" /></div><aside className="bespoke-summary"><span className="eyebrow">Current configuration</span><h2>{selected.name}<br /><em>{selected.short}</em></h2>{review.slice(0, 3).map(([key, value]) => <div className="bespoke-summary__line" key={key}><span>{key}</span><strong>{value}</strong></div>)}<p>Every choice updates this study immediately and is kept in this browser for review.</p><ArrowLink href={`/watch/${selected.slug}`}>Examine the photographed reference</ArrowLink></aside></div></section><section className="bespoke-review" id="review"><div><SectionLabel index="05">Your configuration</SectionLabel><h2>Resolved<br /><em>for conversation.</em></h2><p>A precise session record for a private discussion, not a reservation, order, or catalogue confirmation.</p></div><div><div className="bespoke-review__ledger">{review.map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div><div className="bespoke-review__id">{configurationReference}</div><p>Stored only in this browser until you reset it or end the session.</p><div className="bespoke-review__actions"><button type="button" onClick={() => { sessionStorage.setItem(bespokeStorageKey, JSON.stringify(configuration)); setSaved(true); }}><Save size={14} /> Save configuration</button><button type="button" onClick={reset}><RotateCcw size={14} /> Reset configuration</button><a className="button-primary" href="#consultation">Request bespoke consultation <ArrowUpRight size={14} /></a></div>{saved && <p className="bespoke-saved" role="status">Configuration saved in this browser.</p>}</div></section></div></main>
    <section className="bespoke-request section-dark" id="consultation"><div className="section-wrap">{requested ? <div className="request-confirmation" aria-live="polite"><div className="request-confirmation__mark"><Check size={22} /></div><span className="eyebrow">Conversation forwarded for review</span><h2>A starting point<br /><em>for review.</em></h2><p>Your configuration notes were forwarded to the SAMAY concierge for review. No appointment, configuration, or order is confirmed until the house replies.</p>{appointment?.isActive && appointment.bookingPageUrl ? <a className="button-primary" href={appointment.bookingPageUrl} target="_blank" rel="noreferrer">Choose a viewing time</a> : <Link href="/contact" className="arrow-link arrow-link--dark">Contact the house <ArrowUpRight size={15} /></Link>}</div> : <form className="bespoke-request__grid" onSubmit={submit} noValidate><div><SectionLabel index="06" dark>Continue by conversation</SectionLabel><h2>Bring the<br /><em>study closer.</em></h2><p>Share the configuration ID with the occasion around it. Every final possibility is reviewed individually.</p></div><div className="bespoke-request__form"><label><span>Name</span><input name="name" required autoComplete="name" placeholder="Your name" /></label><label><span>Email</span><input name="email" required type="email" autoComplete="email" placeholder="Your email address" /></label><label><span>Occasion</span><input name="occasion" placeholder="A birthday, a new chapter, simply because" /></label><aside className="form-handoff form-handoff--dark"><span>Configuration ID</span><p>{configurationReference} will travel with this request. Availability and delivery are not implied.</p></aside>{error && <p className="form-error form-error--dark" role="alert">{error}</p>}<button className="button-primary" disabled={requestMutation.isPending}>{requestMutation.isPending ? "Forwarding consultation" : "Request a consultation"} <ArrowUpRight size={15} /></button></div></form>}</div></section>
  </div>;
}
