/* Atelier Obsidian: boutique rooms are quiet, appointment-led spaces for examining the object. */
import { ArrowUpRight } from "lucide-react";
import { ArrowLink, SectionLabel } from "@/components/SiteShell";
import { boutiques } from "@/lib/samayData";

const boutiqueImage = "/manus-storage/samay-boutique-interior_656f10ed.jpg";

export default function Boutique() {
  return <div className="flagship-page boutique-page"><section className="boutique-hero section-dark"><div className="boutique-hero__image"><img src={boutiqueImage} alt="SAMAY private viewing room with a single watch on a stone plinth" /></div><div className="boutique-hero__copy"><span className="eyebrow">SAMAY / By appointment</span><h1>The object,<br /><em>in the room.</em></h1><p>Quiet rooms for looking properly: one watch, a loupe, and enough time for the material to change.</p><ArrowLink href="/inquiry" dark>Arrange a private viewing</ArrowLink></div></section><section className="boutique-list section-paper"><div className="section-wrap"><SectionLabel index="01">The salons</SectionLabel><div className="boutique-list__head"><h2>Three rooms.<br /><em>One point of view.</em></h2><p>Geneva, Paris, and New York hold the SAMAY point of view: a considered setting for comparing metal, leather, movement, and light.</p></div><div className="boutique-cards">{boutiques.map((place) => <article className="boutique-card" key={place.city}><span className="eyebrow">SAMAY / {place.city}</span><h3>{place.city}</h3><p>{place.note}</p><div><span>{place.hours}</span><span>{place.detail}</span></div><ArrowUpRight size={17} strokeWidth={1.1} /></article>)}</div></div></section><section className="boutique-note section-dark"><div className="section-wrap boutique-note__grid"><div><SectionLabel index="02" dark>Bring the question</SectionLabel><h2>Come with<br /><em>curiosity.</em></h2></div><div><p>Compare the way a steel case catches a window, how a strap settles against the wrist, or how a movement reads under a loupe. The appointment is about clarity, not pressure.</p><ArrowLink href="/contact" dark>Contact the house</ArrowLink></div></div></section></div>;
}
