/* Atelier Obsidian: craft is described through gestures, surfaces, and inspection—not spectacle or false provenance. */
import { ArrowUpRight } from "lucide-react";
import { ArrowLink, SectionLabel } from "@/components/SiteShell";
import { craftSteps } from "@/lib/samayData";

const toolsImage = "/manus-storage/samay-atelier-tools_ad9fdca5.jpg";
const movementImage = "/manus-storage/samay-movement-study_129e7db4.jpg";

export default function Craft() {
  return <div className="flagship-page craft-page"><section className="flagship-hero section-dark"><div className="flagship-hero__copy"><span className="eyebrow">SAMAY / Craft</span><h1>Four gestures.<br /><em>One object.</em></h1><p>Craft is the distance between an idea and the moment it becomes easy to wear.</p></div><div className="flagship-hero__stamp">SM / 2026<br />WORKSHOP LIGHT</div></section><section className="craft-intro section-paper"><div className="section-wrap craft-intro__grid"><div><SectionLabel index="01">The discipline of less</SectionLabel><h2>Nothing is<br /><em>decorative.</em></h2></div><div><p className="lead-copy">A surface has to earn its reflection. A hand has to earn its place. We keep the sequence close to the object so the decisions remain legible.</p><p>Atelier work stays close to tools, benches, materials, and the quiet hours between finishing and inspection.</p><ArrowLink href="/atelier">Enter the atelier</ArrowLink></div></div></section><section className="craft-steps-page section-dark"><div className="section-wrap"><SectionLabel index="02" dark>How we work</SectionLabel><div className="craft-steps-page__grid">{craftSteps.map(([number, title, body]) => <article className="craft-step-card" key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p><ArrowUpRight size={17} strokeWidth={1.1} /></article>)}</div></div></section><section className="craft-gallery section-paper"><div className="craft-gallery__image"><img src={toolsImage} alt="Watchmaking tools and a case on a graphite bench" /></div><div className="craft-gallery__copy"><SectionLabel index="03">Surface / pressure / return</SectionLabel><h2>The hand<br /><em>leaves a trace.</em></h2><p>Brushing, polishing, regulating, and returning are not separate effects. They are one continuous conversation with the material.</p><ArrowLink href="/service">Read about care</ArrowLink></div><div className="craft-gallery__detail"><img src={movementImage} alt="Mechanical movement study" /><span>Movement study / SM-101</span></div></section></div>;
}
