/* Atelier Obsidian home: a cinematic entry, material-first storytelling, and quiet invitation. */
// Atelier Obsidian structural pass: home is the canonical composition test—one grid, two editorial modes, no ornamental drift.
import { ArrowDown, ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { ArrowLink, SectionLabel } from "@/components/SiteShell";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { ContentFrame, EditorialSplit, ImageFrame } from "@/components/EditorialPrimitives";
import { ImageWithFallback } from "@/components/ImageWithFallback";
import { ProductCard } from "@/components/ProductCard";
import { journalEntries, watches } from "@/lib/samayData";

const heroImage = "/manus-storage/samay-hero-atelier_246de2bd.jpg";
const materialImage = "/manus-storage/samay-material-library_7379b84b.jpg";
const movementImage = "/manus-storage/samay-movement-caseback_08f1bc8b.jpg";
const boutiqueImage = "/manus-storage/samay-boutique-interior_656f10ed.jpg";

export default function Home() {
  return <div className="home-page">
    <section className="hero">
      <ImageWithFallback className="hero__image" src={heroImage} fallbackSrc={watches[0].image} alt="SAMAY Meridian watch on a dark stone plinth" fetchPriority="high" loading="eager" />
      <div className="hero__veil" />
      <div className="hero__content"><p className="eyebrow hero__eyebrow">SAMAY / Contemporary horology</p><h1>A study in<br /><em>proportion.</em></h1><p className="hero__intro">A contemporary watch house shaped by light, material, and the discipline of less.</p><div className="hero__actions"><ArrowLink href="/collection" dark>Enter the collection</ArrowLink><Link href="/about" className="text-link text-link--light">Discover the house <ArrowUpRight size={14} strokeWidth={1.2} /></Link></div></div>
      <div className="hero__rail"><span>SM / 2026</span><span className="hero__rail-line" /><span>Geneva · Paris</span></div><div className="hero__scroll"><ArrowDown size={15} strokeWidth={1.1} /><span>Scroll to examine</span></div>
    </section>
    <section className="manifesto section-dark"><SectionLabel index="01" dark>The house</SectionLabel><div className="manifesto__grid"><div className="manifesto__statement"><div className="manifesto__dial-study"><div className="manifesto__dial-visual" aria-hidden="true"><span className="manifesto__dial-orbit manifesto__dial-orbit--outer" /><span className="manifesto__dial-orbit manifesto__dial-orbit--inner" /><span className="manifesto__dial-halo" /><span className="manifesto__dial-mark manifesto__dial-mark--north" /><span className="manifesto__dial-mark manifesto__dial-mark--east" /><span className="manifesto__dial-mark manifesto__dial-mark--south" /><span className="manifesto__dial-mark manifesto__dial-mark--west" /><span className="manifesto__dial-hand manifesto__dial-hand--hour" /><span className="manifesto__dial-hand manifesto__dial-hand--minute" /><span className="manifesto__dial-hub" /></div><span className="manifesto__dial-index manifesto__dial-index--one" aria-hidden="true">01</span><span className="manifesto__dial-index manifesto__dial-index--two" aria-hidden="true">27</span><span className="manifesto__dial-caption" aria-hidden="true">A study in<br />quiet measure</span><Tooltip><TooltipTrigger asChild><button className="manifesto__dial-note" type="button" aria-label="View atelier design details">Form<br />follows time</button></TooltipTrigger><TooltipContent side="left" sideOffset={12} className="manifesto__dial-tooltip">The study maps a 27-part minute track, concentric steel tolerances, and the unobstructed space reserved for a dial to breathe.</TooltipContent></Tooltip></div><h2>Time, made<br /><em>tangible.</em></h2></div><div className="manifesto__copy"><p className="lead-copy">SAMAY is a contemporary watch house for those who notice what remains when ornament falls away.</p><p>We begin with proportion. A case line that holds light. A dial that leaves room for the eye. A movement that earns its place beneath the surface. Every decision is made to be felt before it is explained.</p><ArrowLink href="/about" dark>Read our point of view</ArrowLink></div></div><div className="manifesto__line" /><div className="manifesto__foot"><span>01 / 07</span><span>Objects for considered hours</span><span>Scroll to continue</span></div></section>
    <section className="featured section-paper"><ContentFrame><SectionLabel index="02">The collection</SectionLabel><div className="featured__head"><h2>Objects in<br /><em>quiet motion.</em></h2><p>Three references. One point of view. Each SAMAY watch is finished in small batches and offered by private request.</p><ArrowLink href="/collection">View all references</ArrowLink></div></ContentFrame><div className="featured__stage"><ProductCard watch={watches[0]} featured /><div className="featured__side-note"><span className="eyebrow">No. 01 / Meridian</span><p>The evening watch, reduced to the line of its case and the warmth of its dial.</p><span className="side-note__rule" /></div></div></section>
    <section className="material-story"><div className="material-story__image"><ImageWithFallback className="material-story__image-source" src={materialImage} fallbackSrc={heroImage} alt="Macro study of graphite, steel, and warm ivory surfaces" loading="lazy" /><div className="material-story__caption"><span>Light study / 04</span><span>Stone · steel · shadow</span></div></div><div className="material-story__copy section-dark"><SectionLabel index="03" dark>Material studies</SectionLabel><h2>Nothing is<br /><em>accidental.</em></h2><p>From the curve of a lug to the resistance of a crown, the small decisions become the character of the whole. We work with brushed steel, smoked surfaces, natural leather, and the particular silence of warm ivory.</p><ArrowLink href="/materials" dark>Enter the material archive</ArrowLink></div></section>
    <EditorialSplit tone="dark" className="home-movement"><ImageFrame className="home-movement__image" role="movement" src={movementImage} fallbackSrc={materialImage} alt="Open mechanical movement on a graphite workbench" /><div className="home-movement__copy"><SectionLabel index="04" dark>The movement</SectionLabel><h2>Precision<br /><em>underneath.</em></h2><p>The mechanism is not a spectacle. It is the reason the object feels alive: a sequence of surfaces, tolerances, and small returns of energy.</p><div className="home-movement__meta"><ArrowLink href="/movement" dark>Examine the movement</ArrowLink><span>SM-101 / 60 hours</span></div></div></EditorialSplit>
    <section className="journal-preview section-paper"><div className="section-wrap"><SectionLabel index="05">The journal</SectionLabel><div className="journal-preview__head"><h2>Notes from<br /><em>the workbench.</em></h2><ArrowLink href="/journal">Read the journal</ArrowLink></div><div className="journal-preview__grid">{journalEntries.map((entry) => <Link key={entry.slug} href={`/journal/${entry.slug}`} className="journal-tile"><div className="journal-tile__image"><img src={entry.image} alt="" /></div><div className="journal-tile__meta"><span>{entry.index} / {entry.category}</span><span>{entry.date}</span></div><h3>{entry.title}</h3><p>{entry.excerpt}</p></Link>)}</div></div></section>
    <EditorialSplit tone="dark" className="boutique-invite"><ImageFrame className="boutique-invite__image" role="architectural" src={boutiqueImage} fallbackSrc={movementImage} alt="SAMAY private viewing room with a single watch on a stone plinth" /><div className="boutique-invite__copy section-dark"><SectionLabel index="06" dark>By appointment</SectionLabel><h2>The object,<br /><em>in the room.</em></h2><p>See the collection beneath a loupe, compare a strap by hand, or spend a longer hour with the movement. The SAMAY salons are rooms made for that kind of attention.</p><ArrowLink href="/boutique" dark>Explore the boutiques</ArrowLink></div></EditorialSplit>
    <section className="home-cta section-dark"><ContentFrame className="home-cta__inner"><span className="eyebrow">A private introduction</span><h2>Some objects<br /><em>are better seen.</em></h2><p>Begin a private viewing conversation with the house and bring the reference that has caught your eye.</p><ArrowLink href="/inquiry" dark>Request a private viewing</ArrowLink></ContentFrame></section>
  </div>;
}
