// Atelier Obsidian reminder: the article is a reading room — long-form typography, clear escape paths, and image-led pacing.

import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Link, useRoute } from "wouter";
import { ArrowLink, SectionLabel } from "@/components/SiteShell";
import { findJournal, watches } from "@/lib/samayData";

export default function JournalArticle() {
  const [, params] = useRoute("/journal/:slug");
  const entry = findJournal(params?.slug);
  return <article className="journal-article section-paper"><section className="article-hero section-dark"><div className="article-hero__inner"><Link href="/journal" className="back-link"><ArrowLeft size={15} strokeWidth={1.15} /> Back to journal</Link><div className="article-hero__grid"><div><span className="eyebrow">{entry.index} / {entry.category} · {entry.date}</span><h1>{entry.title}</h1><p>{entry.excerpt}</p></div><div className="article-hero__index">SAMAY<br />Journal<br />Issue 01</div></div></div></section><div className="article-image"><img src={entry.image} alt="" /><div><span>Field note / {entry.index}</span><span>Read slowly</span></div></div><section className="article-body section-wrap"><SectionLabel index="01">The note</SectionLabel><div className="article-body__grid"><div className="article-body__intro"><p className="article-kicker">A case is not a container. It is a sequence of decisions about light, pressure, and the wrist.</p></div><div className="article-copy"><p>There is a moment when a watch stops being a collection of parts and becomes an object with a point of view. It happens in the relationship between the case and the dial, where a line of reflected light determines whether the whole thing feels deliberate or merely assembled.</p><p>At SAMAY, we start with the silhouette. The first drawing is not a feature list; it is a study in what the eye will understand in the first second, and what it may return to after a lifetime. A lug turns by a degree. A bevel narrows. A crown moves closer to the wrist.</p><blockquote>“The eye should discover the finishing before the specification explains it.”</blockquote><p>Once the proportions are right, the material can begin to speak. Brushing catches light in one direction. Polished edges interrupt it. Leather holds the last warmth of the day. The work is not to make every surface visible; it is to give each surface a reason to be there.</p><p>That is why a SAMAY watch is intentionally quiet. It leaves space for the owner to complete the object with attention.</p></div></div></section><section className="article-related section-dark"><div className="section-wrap"><SectionLabel index="02" dark>Continue the conversation</SectionLabel><div className="article-related__grid"><div><span className="eyebrow">Object / No. 01</span><h2>See the proportions<br /><em>in the metal.</em></h2><ArrowLink href={`/watch/${watches[0].slug}`} dark>Examine Meridian</ArrowLink></div><div className="article-related__image"><img src={watches[0].image} alt={`${watches[0].name} watch`} /></div></div></div></section></article>;
}
