/* Atelier Obsidian: technical information is presented as an editorial study, with real vocabulary and no sci-fi interface. */
import { ArrowUpRight } from "lucide-react";
import { ArrowLink, SectionLabel } from "@/components/SiteShell";
import { movementSpecs } from "@/lib/samayData";

const movementImage = "/manus-storage/samay-movement-caseback_08f1bc8b.jpg";
const dialImage = "/manus-storage/samay-macro-dial_8993792c.jpg";

export default function Movement() {
  return <div className="flagship-page movement-page"><section className="movement-hero section-dark"><div className="movement-hero__image"><img src={movementImage} alt="Open mechanical watch movement with hand-finished bridges" /></div><div className="movement-hero__copy"><span className="eyebrow">SAMAY / The movement</span><h1>Alive<br /><em>underneath.</em></h1><p>The mechanism is not hidden to make the watch mysterious. It is beneath the surface because that is where the work belongs.</p><ArrowLink href="#calibre" dark>Read the calibre</ArrowLink></div></section><section className="movement-reading section-paper" id="calibre"><div className="section-wrap"><SectionLabel index="01">SM-101 / hand-wound</SectionLabel><div className="movement-reading__intro"><h2>A quiet<br /><em>architecture.</em></h2><p className="lead-copy">Small seconds, twin barrel, and a deliberately low frequency. The SM-101 keeps its energy where the wrist can feel it: in the evenness of the hand.</p></div><div className="movement-specs">{movementSpecs.map(([label, value]) => <div className="movement-spec" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section><section className="movement-detail section-dark"><div className="movement-detail__copy"><SectionLabel index="02" dark>What the loupe finds</SectionLabel><h2>Finishing<br /><em>before flourish.</em></h2><p>The bridges are hand-bevelled, the main plate is circularly grained, and the rotor is restrained so the architecture remains easy to read. Technical detail is allowed to feel like material, not decoration.</p><ArrowLink href="/craft" dark>See the craft sequence</ArrowLink></div><div className="movement-detail__image"><img src={dialImage} alt="Macro view of a warm ivory watch dial" /><span>Dial / case / hand</span></div></section><section className="movement-close section-paper"><div className="section-wrap"><SectionLabel index="03">A mechanism in context</SectionLabel><div className="movement-close__grid"><div><h2>60 hours<br /><em>of return.</em></h2><p>When fully wound, Meridian's movement keeps its reserve through a second evening. It is a practical measure, not a promise of drama.</p></div><div className="movement-close__note"><span className="eyebrow">SM-101</span><p>Designed for legibility, serviceability, and the small pleasure of winding a watch by hand.</p><ArrowLink href="/watch/meridian">Examine Meridian</ArrowLink></div></div></div></section></div>;
}
