/* Atelier Obsidian: service is written as a reassuring continuity promise, with no invented accreditation or operational claims. */
import { ArrowUpRight } from "lucide-react";
import { ArrowLink, SectionLabel } from "@/components/SiteShell";
import { servicePrinciples } from "@/lib/samayData";

const serviceImage = "/manus-storage/samay-service-bench_75bbbccb.jpg";

export default function Service() {
  return <div className="flagship-page service-page"><section className="service-hero section-paper"><div className="section-wrap service-hero__grid"><div><SectionLabel index="01">Care / continuity</SectionLabel><h1>The time<br /><em>after purchase.</em></h1><p>A watch becomes yours through the ordinary rituals: winding, wearing, cleaning, and knowing when to begin a care conversation.</p></div><div className="service-hero__image"><img src={serviceImage} alt="Watch service bench with loupe, gloves, tools, strap, and steel case" /><span>Service bench / 02</span></div></div></section><section className="service-principles section-dark"><div className="section-wrap"><SectionLabel index="02" dark>Our service vocabulary</SectionLabel><div className="service-principles__grid">{servicePrinciples.map(([title, body]) => <article key={title}><span className="eyebrow">{title}</span><h2>{title === "Care" ? "Keep it close." : title === "Maintenance" ? "Return it slowly." : title === "Continuity" ? "Leave a record." : "Change the contact."}</h2><p>{body}</p><ArrowUpRight size={16} strokeWidth={1.1} /></article>)}</div></div></section><section className="service-details section-paper"><div className="section-wrap service-details__grid"><div><SectionLabel index="03">Care policy</SectionLabel><h2>Care,<br /><em>made clear.</em></h2><p>A service conversation can frame questions about inspection, regulation, cleaning, and recordkeeping. Any approved coverage, scope, service interval, or certificate detail is confirmed directly with the house.</p></div><div className="service-accordion"><details open><summary>What happens at a service?</summary><p>Begin by describing the object and the question. The house reviews the request and confirms whether inspection, cleaning, regulation, or another course of care is appropriate before any work is arranged.</p></details><details><summary>Can I replace the strap?</summary><p>Tell the house how the watch is worn and what the season asks for. Compatibility, availability, and any recommendation are confirmed through the service conversation.</p></details><details><summary>How do I contact the house?</summary><p>Begin with the service conversation. This page prepares the question; no payment, shipping label, or service work is created here.</p></details><ArrowLink href="/contact">Start a service conversation</ArrowLink></div></div></section></div>;
}
